version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - my_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./node-exporter.yml:/etc/prometheus/node-exporter.yml
    networks:
      - my_network

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    networks:
      - my_network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
